version: '2.1'
jobs:
    dockerhub:
        docker:
            - image: docker:18.09.7-git
        working_directory: ~/repo
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Authenticate to dockerhub
                command: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_LOGIN} --password-stdin
            - run:
                name: Build and push docker image
                command: |
                    version=latest
                    if [[ ! -z ${CIRCLE_TAG} ]]; then \
                        version=${CIRCLE_TAG}; \
                    fi

                    docker_tag=${DOCKERHUB_ORGANIZATION}/${CIRCLE_PROJECT_REPONAME}:${version}

                    docker build . -t ${docker_tag}
                    docker push ${docker_tag}

workflows:
    version: '2.1'
    dockerhub:
        jobs:
            - dockerhub:
                context: global
                filters:
                    tags:
                        only: /^[0-9]+.[0-9]+.[0-9]+$/
                    branches:
                        only: master
